sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python
python:
  - "3.5"

env:
  - VERSION="12.0" ODOO_REPO="OCA/OCB"
  - VERSION="12.0" ODOO_REPO="odoo/odoo"


install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - pip install coveralls flake8
  - pip install magento
  - pip install beautifulsoup4
  - git clone https://github.com/OCA/connector ${HOME}/connector -b ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_flake8
  - travis_run_tests ${VERSION}

after_success:
  coveralls
